name: Build and Release Extensions

on:
  push:
    tags:
      - 'v*'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' manifest.json

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add manifest.json
          git commit -m "Bump version to ${{ steps.get_version.outputs.VERSION }}"
          git push

  build-chrome:
    needs: [update-manifest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Chrome extension ZIP
        run: |
          zip -r ftapi-dev-helper-chrome-${{ steps.get_version.outputs.VERSION }}.zip . -x "*.git*" -x ".github/*"

      - name: Upload Chrome extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension
          path: ftapi-dev-helper-chrome-${{ steps.get_version.outputs.VERSION }}.zip

  build-firefox:
    needs: [update-manifest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Firefox extension ZIP
        run: |
          zip -r ftapi-dev-helper-firefox-${{ steps.get_version.outputs.VERSION }}.zip . -x "*.git*" -x ".github/*"

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: firefox-extension
          path: ftapi-dev-helper-firefox-${{ steps.get_version.outputs.VERSION }}.zip

  create-release:
    needs: [update-manifest, build-chrome, build-firefox]
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download Chrome extension
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension

      - name: Download Firefox extension
        uses: actions/download-artifact@v3
        with:
          name: firefox-extension

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ftapi-dev-helper-chrome-${{ steps.get_version.outputs.VERSION }}.zip
            ftapi-dev-helper-firefox-${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
