name: Build and Release Extensions

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release:
    # Only run if the PR was merged (not just closed) and the PR title contains "Bump version to"
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Bump version to')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Extract version from PR title
        id: get_version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo $PR_TITLE | sed -n 's/Bump version to \(.*\)/\1/p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Chrome extension ZIP
        run: |
          zip -r ftapi-dev-helper-chrome-${{ steps.get_version.outputs.VERSION }}.zip . -x "*.git*" -x ".github/*"

      - name: Create Firefox extension ZIP
        run: |
          zip -r ftapi-dev-helper-firefox-${{ steps.get_version.outputs.VERSION }}.zip . -x "*.git*" -x ".github/*"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ftapi-dev-helper-chrome-${{ steps.get_version.outputs.VERSION }}.zip
            ftapi-dev-helper-firefox-${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}